# SPDX-FileCopyrightText: Copyright (c) 2018-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  SuggestExtensions: false
Minitest/EmptyLineBeforeAssertionMethods:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Metrics/AbcSize:
  Max: 50
Metrics/MethodLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/ParameterLists:
  Max: 10
Layout/ParameterAlignment:
  Enabled: false
plugins:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-performance
